version: "3"
services:
  cadastro_perguntas:
    container_name: jogodabiblia_cadastro_perguntas
    restart: always
    build:
      context: cadastro_perguntas
      dockerfile: Dockerfile
    ports:
      - "${CADASTRO_PERGUNTAS_PORT}:8000"
    volumes:
      - ./cadastro_perguntas:/usr/src/app
    command: python app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: jogodabiblia_db
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./initial_data:/initial_data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  nginx:
    container_name: jogodabiblia_nginx
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - cadastro_perguntas