version: "3"
services:
  cadastro_perguntas:
    container_name: jogodabiblia_cadastro_perguntas
    restart: always
    build:
      context: cadastro_perguntas
      dockerfile: Dockerfile
    ports:
      - "${CADASTRO_PERGUNTAS_PORT}:8000"
    volumes:
      - ./cadastro_perguntas:/usr/src/app
    command: python app/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: mysql
    container_name: jogodabiblia_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./initial_data:/initial_data
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: admin
      MYSQL_PASSWORD: "${DB_ADMIN_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
  phpmyadmin:
    image: phpmyadmin
    container_name: jogodabiblia_pma
    restart: always
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on: 
      - db
  nginx:
    container_name: jogodabiblia_nginx
    restart: always
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - cadastro_perguntas